[build]
  command = "npm install && npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "14" # Optional, agar specific Node.js version chahiye

[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

